# AUTO BUILDS #
# From https://github.com/Poeschl/Hassio-Addons
# name: slug/filename ; could be slug/config.* for all files
epicgamesfree: epicgamesfree/config.* # Image : yes
free_games_claimer: free_games_claimer/config.* # Image : yes
plex: plex/config.* # Image : yes
plex_meta_manager: plex_meta_manager/config.* # Image : yes
qbittorrent: qbittorrent/config.* # Image : yes
